FROM mysql:8.0

# 2. Thiết lập sẵn Mật khẩu và Tài khoản (Hardcode)
# Lưu ý: Cách này tiện lợi cho Dev/Học tập, nhưng không an toàn cho Production
ENV MYSQL_ROOT_PASSWORD=123
ENV MYSQL_DATABASE=auth-db
ENV MYSQL_USER=tuan
ENV MYSQL_PASSWORD=1

# 3. Mở cổng 3306
EXPOSE 3306